# Generated by Django 4.2.1 on 2023-05-28 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('PENDING', 'Pending'), ('CUSTOMER', 'Customer'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('MANAGR', 'Manager'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email_signature', models.TextField(max_length=1333)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')])),
                ('mobile', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')])),
                ('home_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')])),
                ('password_reset_attempt', models.PositiveSmallIntegerField(default=0)),
                ('password_reset_lockout_date', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('email_opt_out', models.BooleanField(default=False)),
                ('home_phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
